# ===== Correo (opcional) =====
ADMIN_EMAIL="juan21pardo@gmail.com"
SMTP_HOST="smtp.gmail.com"
SMTP_PORT="587"
SMTP_USER="juan21pardo@gmail.com"
SMTP_PASS="zehzhveqohewxuor"
SMTP_FROM="juan21pardo@gmail.com"